name:                practice-gloss
version:             0.1.0.0
github:              "master-q/practice-gloss"
license:             BSD3
author:              "Kiwamu Okabe"
maintainer:          "kiwamu@debian.or.jp"
copyright:           "2018 Kiwamu Okabe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on Github at <https://github.com/master-q/practice-gloss#readme>

dependencies:
- base >= 4.7 && < 5
- gloss

library:
  source-dirs: src

executables:
  practice-gloss-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - practice-gloss
